BEGIN
    EXECUTE IMMEDIATE '
        CREATE TABLE pydapper.task (
            id NUMBER GENERATED BY DEFAULT AS IDENTITY,
            description VARCHAR(255) NOT NULL,
            due_date DATE NOT NULL,
            owner_id NUMBER NOT NULL,

            PRIMARY KEY (id),

            CONSTRAINT fk_owner
                FOREIGN KEY (owner_id)
                REFERENCES owner(id)
        )';
    EXCEPTION
        WHEN OTHERS THEN IF SQLCODE = -955 THEN NULL; ELSE RAISE; END IF;
END;