name: latest changes

on:
  pull_request_target:
    branches:
      - main
    types:
      - closed
  workflow_dispatch:
    inputs:
      number:
        description: PR number
        required: true

jobs:
  latest-changes:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          # To allow latest-changes to commit to main
          token: ${{ secrets.ACTIONS_TOKEN }}
      - uses: docker://tiangolo/latest-changes:0.3.2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          latest_changes_file: docs/release_notes.md
          latest_changes_header: '## Latest Changes\n\n'
          debug_logs: true